#define SQL_USER_TABLE_1 "CREATE TABLE user_info(ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(24) NOT NULL, PASS VARCHAR(24) NOT NULL, USERIP VARCHAR(16) NOT NULL, ADMIN INT(1) NOT NULL, CLANID INT(2) NOT NULL, MONEY INT(10) NOT NULL, LEVEL INT(3) NOT NULL, EXP INT(3) NOT NULL) ENGINE=INNODB"
#define SQL_USER_TABLE_2 "ALTER TABLE user_info ADD(KILLS INT(5) NOT NULL, DEATHS INT(5) NOT NULL, SKIN INT(5) NOT NULL, WEP1 INT(2) NOT NULL, WEP2 INT(2) NOT NULL, WEP3 INT(2) NOT NULL, INTERIOR INT(2) NOT NULL, WORLD INT(1) NOT NULL)"
#define SQL_USER_TABLE_3 "ALTER TABLE user_info ADD(POS_X DECIMAL (10,5) NOT NULL, POS_Y DECIMAL (10,5) NOT NULL, POS_Z DECIMAL (10,5) NOT NULL, ANGLE DECIMAL (10,5) NOT NULL, HP DECIMAL (3,0) NOT NULL, AM DECIMAL (3,0) NOT NULL)"

#define SQL_CLAN_TABLE "CREATE TABLE clan_info(ID INT PRIMARY KEY AUTO_INCREMENT,NAME VARCHAR(50) NOT NULL,LEADER_NAME VARCHAR(24) NOT NULL,KILLS INT(5) NOT NULL,DEATHS INT(5) NOT NULL,COLOR INT(10) NOT NULL,ZONE_LENGTH INT(3) NOT NULL) ENGINE=INNODB"
#define SQL_ZONE_TABLE "CREATE TABLE zone_info(ID INT PRIMARY KEY AUTO_INCREMENT,OWNER_CLAN INT(3) NOT NULL) ENGINE=INNODB"
#define SQL_VEHICLE_TABLE "CREATE TABLE vehicle_info(ID INT PRIMARY KEY AUTO_INCREMENT,NAME VARCHAR(24) NOT NULL,POS_X DECIMAL (10,5) NOT NULL,POS_Y DECIMAL (10,5) NOT NULL,POS_Z DECIMAL (10,5) NOT NULL,ANGLE DECIMAL (10,5) NOT NULL,COLOR1 INT(3) NOT NULL,COLOR2 INT(3) NOT NULL) ENGINE=INNODB;"
#define SQL_HOUSE_TABLE "CREATE TABLE house_info(ID INT PRIMARY KEY AUTO_INCREMENT,NAME VARCHAR(24) NOT NULL,OPEN INT(1) NOT NULL,ENTER_POS_X DECIMAL (10,5) NOT NULL,ENTER_POS_Y DECIMAL (10,5) NOT NULL,ENTER_POS_Z DECIMAL (10,5) NOT NULL,LEAVE_POS_X DECIMAL (10,5) NOT NULL,LEAVE_POS_Y DECIMAL (10,5) NOT NULL,LEAVE_POS_Z DECIMAL (10,5) NOT NULL) ENGINE=INNODB"
#define SQL_WEAPON_TABLE "CREATE TABLE weapon_info(ID INT PRIMARY KEY AUTO_INCREMENT,USER_ID INT NOT NULL,MODEL INT(4) NOT NULL) ENGINE=INNODB"

